name: dart_console_app
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=3.5.2 <4.0.0'

dependencies:
  riverpod: ^2.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0